### ISSUE TITLE
Current version throws exception with Openfire 4.3

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/openfire-motd-plugin#1]
Report: https://discourse.igniterealtime.org/t/exception-in-motd-plugin-after-enter-users-motd-properties-in-admin-panel/84035

MoTD 1.2.1 works ok with Openfire 4.2.3, but with 4.3 shows exception when going to its menu in Users\Groups > MoTD Properties:

java.lang.NoSuchMethodError: org.apache.jasper.runtime.JspContextWrapper.(Ljavax/servlet/jsp/JspContext;Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/Map;)V
at org.apache.jsp.tag.webadmin.contentBox_tagx.setJspContext(contentBox_tagx.java:37)
at org.jivesoftware.openfire.plugin.motd.motd_002dform_jsp._jspx_meth_admin_005fcontentBox_005f0(motd_002dform_jsp.java:680)
at org.jivesoftware.openfire.plugin.motd.motd_002dform_jsp._jspService(motd_002dform_jsp.java:169)
at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at org.jivesoftware.openfire.container.PluginServlet.handleJSP(PluginServlet.java:395)
at org.jivesoftware.openfire.container.PluginServlet.service(PluginServlet.java:109)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
at org.jivesoftware.admin.PluginFilter.doFilter(PluginFilter.java:226)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
at org.jivesoftware.admin.AuthCheckFilter.doFilter(AuthCheckFilter.java:216)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
at org.jivesoftware.util.LocaleFilter.doFilter(LocaleFilter.java:73)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
at org.jivesoftware.util.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:49)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
at org.jivesoftware.admin.PluginFilter.doFilter(PluginFilter.java:226)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
at org.jivesoftware.admin.AuthCheckFilter.doFilter(AuthCheckFilter.java:216)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at org.eclipse.jetty.server.Server.handle(Server.java:503)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
at java.lang.Thread.run(Thread.java:748)

**Comment by GregDThomas** [comment]
That will be the same issue covered at https://github.com/igniterealtime/openfire-dbaccess-plugin/issues/2#issuecomment-457510577

**Comment by wrooot** [comment]
Actually this is opposite. DB Access  plugin works with new Openfire, but not with old. MoTD works with old, but not with the new. And now it seems that your assumption on DB Access issue might be off.

**Comment by wrooot** [comment]
Or probably it can be made similar by applying same changes like in DB Access case and then working and not working versions will switch.

**Comment by wrooot** [comment]
Need to release new version and add this to changelog.

**Comment by GregDThomas** [comment]
@wrooot - apologies, I think 5 or 6 issues probably fall under this category. Do we have a (written or otherwise) guide for this sort of thing?

For core Openfire, it appears to be;
Merge the PR, close the issue, assign the issue to the earliest 'next' release the PR was merged in to. 
At release, generate changelog from JIRA

For plugins, as it's not easy to assign an issue to a release like it is with JIRA, so is/should the policy be;
Update the change log, merge the PR. 
At release, close all issues highlighted in the new changelog.

A couple of other options;
a) Make use of Github Milestones to assign issues to. 
b) Introduce a "Pending release" tag which issues could be tagged with.
c) Anything else?

**Comment by guusdk** [comment]
We (well, I) generally try to update the changelog with the PR that introduces the change/fix. To me, it makes sense to close the issue immediately (instead of delaying closing the issue to whenever we release).

I've never given any though to do bookkeeping of issues-to-releases in Github. If milestones work, I'm happy to give that a try.

**Comment by wrooot** [comment]
I have such instructions saved for myself (based on Guus suggestion):
Make changes in source
Edit changelog
Edit pom.xml and make version number without -SNAPSHOT (most plugins already have automatic version in plugin.xml)
>>>plugin's version change doesn't have to be in a separate commit
>>>don't change ModelVersion
Make commit - put GitHub's issue ID as commit message (e.g. #123)
Edit pom.xml, increase version number and add -SNAPHOT
Make commit
Then make PR (although it doesn't have to be the same PR)
After PR is merged, someone has to tag first commit as release on GitHub for it to be released as stable version
Then someone approves commit adding -SNAPSHOT with increased version

I don't have strong opinion on when to close an issue. Could be at once after fixing it.

Milestones looks like a nice feature as well as tags, but maybe a bit of an overkill for plugins. Especially when we have ~50 repos for them.. I would do as simple as possible for now. Just fix a bug, close the issue, update changelog. If not enough fixes to warrant a release, leave as is or do a release.

**Comment by GregDThomas** [comment]
OK, I need to do some work today, but given these are fairly important issues (for Openfire 4.2 users, at least) I will try and get those three plugins released later.

**Comment by GregDThomas** [comment]
Finally got around to updating the changelog / releasing.
